### ISSUE TITLE
docs: preview urls should auto redirect to /docs

### ISSUE THREAD

**Issue by 3v0k4** [magicbell-io/public#14]
On each PR, Vercel deploys a preview. There are a couple of problems with that:

- We don't need a preview if the change happens outside of [/docs](./docs)
- The deployment doesn't work: when I click on "View deployment" I see the error below

<img width="454" alt="Error from Vercel" src="https://user-images.githubusercontent.com/5238698/202147369-2e62a037-8450-473e-a17d-0a6352fef2a4.png">

**Comment by 3v0k4** [comment]
The deployment works. Without access to Vercel, I had to follow my intuition 😄

Adding /docs at the end of the URL shows the deployed docs. Still, that should be more ergonomic.

**Comment by unamashana** [comment]
@3v0k4 feedback duly noted. We will improve this behavior.

**Comment by smeijer** [comment]
The preview urls on a subpath are annoyingly hard to fix. I've tried it in the past, but for some reason never got it working right.

I've added this hack for development a while ago, but that doesn't work on preview urls. Maybe we need a combination of that hack and the redirect? 🤷 

https://github.com/magicbell-io/public/blob/7d4292b32a14973dffb22a19e1700fcf0d890510/docs/pages/_app.tsx#L34-L41

**Comment by smeijer** [comment]
I'm splitting of the issue regarding scoping previews to https://github.com/magicbell-io/public/issues/36, as it's a whole other problem to solve.
